package com.pmu2.exec.infrastrure.db.sql;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

/**
 * Represents a Partant in the database.
 * This entity is mapped to the "partant" table in the database.
 *
 * @author HelderPM
 * @since 1.0
 */
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@EqualsAndHashCode(of = "id")
@Table(name = "partant")
public class PartantEntity {

    /**
     * The unique identifier for the Partant.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the Partant.
     * This field is required and cannot be null.
     *
     * @see jakarta.validation.constraints.NotBlank
     */
    @Column(name = "nom", nullable = false)
    @NotBlank(message = "Your Partant needs a name.")
    private String name;

    /**
     * The number of the Partant.
     * This field is required and cannot be null.
     */
    @Column(name = "numero", nullable = false)
    private int number;

    /**
     * Constructor for creating a new PartantEntity with the given name and number.
     *
     * @param name  The name of the Partant.
     * @param number  The number of the Partant.
     */
    public PartantEntity(String name, int number) {
        this.name = name;
        this.number = number;
    }

}
